::: {.content-visible when-format="html"}
<h2> ようこそ </h2>

**これはオンライン版 [*Deep Learning and Scientific Computing with R `torch`*](https://skeydan.github.io/Deep-Learning-and-Scientific-Computing-with-R-torch/) [Sigrid Keydana](https://divergences.xyz/) 著の部分的な和訳「R torchによる深層学習と科学計算」である。
GitHubリポジトリは [原典](https://github.com/skeydan/Deep-Learning-and-Scientific-Computing-with-R-torch)、[和訳](https://github.com/tenomoto/dlscrtorch/) にある。
原典の紙媒体 [CRC Press](https://doi.org/10.1201/9781003275923) は出版社または [Amazon](https://www.amazon.com/Learning-Scientific-Computing-torch-Chapman/dp/1032231394)のような販売店から購入できる。**

**このオンラインの著作は** <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">**Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License**</a>**でライセンスされている。**
:::

# はじめに {.unnumbered .unlisted}

この本は `torch` 、 PyTorchのRインターフェースについて書かれている。
PyTorchは執筆時点で、主要な機械学習と科学計算フレームワークの一つで、産業や研究の分野で広く使われている。
`torch` を使うと、Rから直接その豊富な機能を使うことができる。
Pythonをインストールすることも、学ぶことすら必要ない。
まだ *若い* プロジェクトだが、 `torch` は既に活発なユーザと開発者のコミュニティがある。
開発者はフレームワーク本体だけでなく、その上に自前のパッケージを構築している。

本書では、三つの部に対応して、三つの目的を達成することを目指している。

最初の目的は `torch` の基礎について丁寧に紹介することである。
基礎とは、それなしには何も動作しない基礎的な構造を指す。
先々では、できるだけ高度な文法構造を使うことになるが、基礎的な機能の動作や、概念について知ることは重要である。
さらに、実用的な観点からは、 必要以上の試行錯誤をしなくて済むように`torch` についてある程度慣れることは重要である。

第二部では、説明した基礎の上に、画像認識、時系列データ、表形式データ、音声分類など、様々な深層学習への応用を探求する。
ここでも、概念的な説明に重点を置いている。
さらに、各章では、自分のアプリケーションに使える「テンプレート」としてのアプローチを紹介している。
適切な場合には、稀ではない「ビッグデータ、巨大モデル、大量計算」の方法とは一線を画して、専門知識の組み込みの重要性についても指摘している。

第三部は、`torch` でできるディープラーニング以外のことを紹介している。
行列計算（例えば、線型回帰問題の解法）、離散フーリエ変換、ウェーブレット解析などである。
ここで、本書の他のどの部分よりも、概念的な記述が非常に重要であると考えている。
その理由について説明する。

一つには、読者の教育的背景が様々であると想定しているからである。
Rが自然科学や応用数学に近い分野で教えられ、使われるようになっているため、例えば、離散フーリエ変換がどのように動作するかの概念的な説明には、あまり恩恵を受けられないと感じる人もいるかもしれない。
一方で、これらのことが未知の領域である可能性がある人もいるだろう。
例えば、文学、文化研究、言語学など、伝統的に経験主義的でない背景を持つ人々である。
もちろん、もし読者が後者に属している場合、本書の説明が概念に焦点を合わせているにもかかわらず、それでも非常に（または非常に）数学的であると感じるかもしれない。
その場合でも、安心してほしい。
確かに、（他の多くの有意義なことを理解するのと同様に）数学的な概念を理解するには長い道のりが必要だが、人生をかけてゆっくり進めばよい。

二つ目に、深層学習が過去10年間のパラダイムであったにもかかわらず、最近の動向は、数学的または専門分野に根差した基盤への関心が再び高まっていることを示している（例えば、@abs-2104-13478　にある体系的に説明や[*Beyond alchemy: A first look at geometric deep learning*](https://blogs.rstudio.com/ai/posts/2021-08-26-geometric-deep-learning/) （錬金術を超えて–幾何学的深層学習ことはじめ） が概念を紹介している幾何学的ディープラーニングアプローチ参照）。
将来、深層学習技術と専門知識を統合する「ハイブリッド」アプローチがますます増えると予想される。
フーリエ変換は消えない。

最後にこの話題に関して重要なことは、全ての章には `torch` のコードを付けたということを言及しておきたい。
例えば、フーリエ変換の場合、専用の機能を使った公式の方法だけでなく、アルゴリズムを自分でコーディングする様々な方法も習得できる。
自作のコードは、驚くほど少ない行数で、非常に印象的なパフォーマンスで実装できる。

簡単に言えば、これが本書から得られるものである。
最後に、一つだけ言及しておきたいことがある。
述べようとしたが、技術的な内容のため、本編ではあまり触れることができなかったことだ。
私たちの社会では、機械/ディープラーニング（「AI」）の採用が増えるにつれ、政府や民間組織による悪用の機会も増えている。
しばしば、悪意がなくても、結果は壊滅的になることがある。
特に、少数派や既に不利な立場にあるグループにとっては、そのような結果は致命的である。
そのため、現在の政治体制では不可避だが、利益を追求することが、最悪の場合疑問の余地のある機能（監視、すべての量的化）を持つ社会を生み出し、最も不公平、差別、深刻な害をもたらす可能性が高い。
ここで、この問題に注意を向けることをお願いすべく、ブログ記事 [*Starting to think about AI Fairness*](https://blogs.rstudio.com/ai/posts/2021-07-15-ai-fairness/) （AI公平性についての考察の試み） を参照して、社会生活や自分の仕事や応用において、この問題に積極的に注意を払っていただきたい。

最後に、感謝の言葉で締めくくりたい。
感謝すべき人々は多すぎるので、誰かを落としてしまうかもしれないが、それでも短く書くことにする。
出版社であるCRC Press（最初に、David GrubbsとCurtis Hill）には、執筆と編集のすべての段階で非常に快適なやり取りをしていただき、感謝している。
そして、以下の人々に対し、この本に関連する支援とそれぞれの役割に対する特別な感謝を表明する。
Daniel Falbel、`torch` の作成者兼メンテナー、この本を詳細にレビューし、多くの技術的問題を助けてくれた。
Tracy Teal、私の上司で、すべての可能な方法で支援し、励ましてくれた。
Posit（旧RStudio）は、雇用主であり、このような仕事で生計を立てることを許してくれる。

Sigrid Keydana
